### PR TITLE
Friendship v1 feature

### PR DESCRIPTION
**Pull request by Misori-simon**
#### This feature has the following changes
- friendship model with user_id and friend_id
- migration for status to friendship table
-  is_friend, friends_group, and add friend methods to user model
- request_friends, friends_group, friend?, accept_friend, decline_friend, available_available_for_request
-  new_request, accept_request, decline_request methods and routes for friendship
-  links to user partial for the various controls
- timeline post for current user and friends

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Status: Changes Required** :red_circle: 
Hello team,

Good job :clap:  However, there are still a few fixes needed.
REQUIRED:
- [x] Posts timeline includes posts written by **logged-in user** **and their friends** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] There is a button to invite user on `single user` page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Add  Unit and Integration tests for Friendship, User and Post model ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))


**Good luck and Happy coding**
Rindra Josia

**Comment by Misori-simon** [comment]
Thanks for the review. The unit integration test is for the next milestone

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
### Hey there :wave: 
###### There are still changes you need to make to ge this milestone approved
- [x] Posts timeline includes posts written by logged-in user and their friends. When you accept a request from a user, that user's post should be visible on your own post page.
- [x] It is clearly stated in the requirement for milestone 5 that you should add unit and integration tests. So please do add them.
#### Request another review when you are done
slack(@ebeagusamuel)

**Comment by Misori-simon** [comment]
Okay yeah. Thanks

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑**
Hello team,
Great work implementing the changes. I can tell how hard you are working.
However, let's make one change.
[REQUIRED] In post controller's index function, current_user_posts and friend_posts should be in one variable. You can either write a scope or a query, that combines the current_user's and his friends' posts. Then there will be no need of separating the two in the index.html.erb.

Make that change and submit for another review.
Happy coding👍👍

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Hello there, great work you've done so far on this project. I liked how you solved all the mentioned issues so perfectly. Congratulations on finishing this milestone, you can now merge to the development branch and move on to the next.

Good luck and happy coding 👨‍💻💻😊

**Comment by Misori-simon** [comment]
Thanks 👍🏿

**Pull request merged**
