### PR TITLE
generate friendship model

### PR DESCRIPTION
**Pull request by Misori-simon**
- generate friendship model with referneces to users table
- add the belong to relationship tp friendship model
- add the has_many relation to the user model
- add the friends method to the user model

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes required**
Hey team!! Good work, however, `in this milestone`, (First) you have to create `ERD` corresponding to your databases then, `in the next milestone`, you can implement all the tasks that you have done on this branch:

- [ ] [REQUIRED]ERD diagram is placed in docs directory ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/erd2.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

As you can see in this screenshot, you are asking code review for **Milestone: docs**

Thanks
Rindra Josia

**Comment by Misori-simon** [comment]
okay, thanks. I haven't found one though. Should I create it?

**Comment by rindrajosia** [comment]
> okay, thanks. I haven't found one though. Should I create it?

Close this branch then and create a new one where you will make your ERD then ask a CRR. Once it is approved, you can open this one and ask for a new CRR corresponding to the right milestone

**Comment by Misori-simon** [comment]
Okay thanks

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Misori-simon  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project looks nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement this project's requirements carefully, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The timeline displays posts from the current logged in user and from his/her friends => Currently it is showing every posts in the system => fix that.
- [ ] As a user I should be able to reject friendship
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Pull request closed without merging**
