### PR TITLE
Erb docs feature

### PR DESCRIPTION
**Pull request by Misori-simon**
- Add ER diagram for ROR socials in doc directory

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#help"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>


- [ ] n/a


</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="close">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>


- [ ] The ERD image should show on the User Model the image link. Please update it.
- [ ] README is not complete, it still has some sections with TBA



</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>


- [x] Nothing more to add.


</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    Julio Añoveros
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="help"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> ... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

**Comment by Misori-simon** [comment]
> [Microverse](https://www.microverse.org/?grsf=kfm2ej)
> 
> #     Changes Required    
> 
> "Fail fast, fail often" and don't let this discourage you, because only by failing do we learn to succeed.
> 
> Review Summary
> 1. [ 100 Awesome work 👏🏼 👏🏼 ](#congrats)
> 2. [ warning Things to Improve ](#mandatory) rotating_light rotating_light
> 3. [ bulbNice to have and other comments ✍🏼 ✍🏼 ](#optional)
> 4. [ 🧔🏼 About your Reviewer ](#contact) (you don't know it... but we are just automated bots robot)
> 5. [ sos  sob Feeling stuck? or Need help? 🙏🏼 🙏🏼 ](#help)
> 
> ### 1.  Awesome work
>  [click to open] Big or little achievements, but achievements at the end. Feel proud that you're learning and improving everyday.
> ### 2.  Things to Improve (or the To-Do list to get the project approved)
>  [click to open] Working on these observations will help you advance and get closer to the goal , postpone them or do them half-ways and they'll haunt you  ... FOREVER!! (It will feel like that, trust me).
> NOTEThis list is or could be divided in what is show in this comment and inline comments posted below.
> 
> ### 3.  Nice to have and other comments
>  [click to open]
> ### 4. 🧔🏼 About your Reviewer
>  [click to open] Say "hello world!" on Slack: @jubaan
> ### 5.   Feeling stuck? or Need help? 🙏🏼 🙏🏼
>  [click to open] Feel stuck?
>  [click to open] Need help?
> 
> Send me a DM in [Microverse](https://www.microverse.org/?grsf=kfm2ej) Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.
> 
> Remember that [Microverse](https://www.microverse.org/?grsf=kfm2ej) has other channels where you can get an answer to your questions:
> 
> 1. The students channel student  in slack,
> 2. your teammates busts_in_silhouette ,
> 3. your mentor 👨🏼 👩🏼 , and
> 4. Student Success school .
> 
> DON'T hesitate to ask!
> 
> If all of the above doesn't help... get a [rubber duck](https://rubberduckdebugging.com/) ... it would be great to own one .
> 
> ## Keep up the great work  and Happy Coding  !!

**Comment by Misori-simon** [comment]
Thanks for the review. I do not understand the first change required of me. concerning the image...

**Comment by Misori-simon** [comment]
I did not update the readme file because I am yet to complete the project upon which i will write a comprehensive readme for it.

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Required Changes ♻🛑**

<hr>

Hello there, your milestone looks good and almost complete, please follow the following points in order to get it approved 🙏😊

- [x] Please update your relations between the Users and the Friendships table to be similar to the given ERD (Think about the associations you're going to implement between these two models in your app)
- [x] Please make sure to edit your Likes table to be exactly as the given one

<hr>

Good luck tho ❤👍

**Comment by Misori-simon** [comment]
Please this milestone is about docs

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @Misori-simon  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
